version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - "echo PWD: && pwd"
      - "echo Listing repo root: && ls -lah"
      - "mvn -v"
      - "mvn clean package -DskipTests"
      - "echo Listing target/: && ls -lah target"
      - "JAR=$(ls target/*.jar | head -n 1)"
      - "echo Using jar: $JAR"
      - "cp \"$JAR\" app.jar"
      - "echo Final files: && ls -lah"

artifacts:
  files:
    - app.jar
    - Procfile
