version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - "echo Starting build in root"
      - "pwd"
      - "ls -lah"
      - "cd aws"
      - "echo Now inside aws directory"
      - "pwd"
      - "ls -lah"
      - "mvn -v"
      - "mvn clean package -DskipTests"
      - "ls -lah target"
      - "JAR=$(ls target/*.jar | head -n 1)"
      - "echo Built jar is $JAR"
      - "cp \"$JAR\" app.jar"
      - "ls -lah app.jar"

artifacts:
  files:
    - aws/app.jar
    - aws/Procfile
  discard-paths: yes
