version: 0.2

phases:
  build:
    commands:
      - cd aws
      - mvn -v
      - mvn clean package -DskipTests
      - cp target/*.jar app.jar

artifacts:
  files:
    - aws/app.jar
    - aws/Procfile
  discard-paths: yes
